services:
  nest-app:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: nest_app_tcc
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
      - /app/node_modules
      - ${FIREBASE_ADMIN_CREDENTIALS_HOST_PATH}:/app/credentials/firebase-admin.json:ro
    env_file:
      - .env
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=${POSTGRES_USER}
      - DB_PASSWORD=${POSTGRES_PASSWORD}
      - DB_NAME=${DATABASE_NAME}
      - FLASK_API_URL=http://flask-app:5000
      - FIREBASE_API_KEY=${FIREBASE_API_KEY}
      - FIREBASE_ADMIN_CREDENTIALS_PATH=/app/credentials/firebase-admin.json
    depends_on:
      - db
      - flask-app

  flask-app:
    build:
      context: ./flask
      dockerfile: Dockerfile
    container_name: flask_app_tcc
    ports:
      - "5000:5000"
    volumes:
      - ./flask:/app
    env_file:
      - .env
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - DATABASE_NAME=${DATABASE_NAME}
      - DB_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${DATABASE_NAME}
    depends_on:
      - db

  db:
    image: postgres:13
    container_name: database
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${DATABASE_NAME}"]
      interval: 10s
      retries: 5

volumes:
  db_data:
