services:
  flask-app:
    build: .
    container_name: flask_app_tcc
    ports:
      - "5000:5000"
    volumes:
      - ./Flask:/app
    env_file:
      - .env
    environment:
      - DB_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${DATABASE_NAME}
    depends_on:
      - db
      # - minio  

  db:
    image: postgres:13
    container_name: database
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}
      - HOST=${DB_HOST}
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      retries: 5
    volumes:
      - db_data:/var/lib/postgresql/data
  
  # minio:
  #   image: minio/minio 
  #   container_name: minio
  #   command: server /data
  #   ports:
  #     - "9000:9000" 
  #   environment:
  #     - MINIO_ROOT_USER=minioadmin
  #     - MINIO_ROOT_PASSWORD=minioadmin
  #   volumes:
  #     - minio_data:/data

volumes:
  db_data: 
  # minio_data:
